# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libgdal-dev libproj-dev libgeos-dev
